### ISSUE TITLE
classfactory()-error sinds 2.2.8

### ISSUE THREAD

**Issue by filipmahieu** [warrieka/geopunt4Qgis#23]
Bij openen QGis (3.16.7) genereert net geüpdate Geopunt-plugin v 2.2.8 fout, geopunt-plugin niet bruikbaar dan :
'Kon plug-in 'geopunt4Qgis' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geopunt4Qgis\__init__.py", line 27, in classFactory
    from .geopunt4qgis import geopunt4Qgis
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geopunt4Qgis\geopunt4qgis.py", line 6, in 
    from .geopunt4QgisAdresdialog import geopunt4QgisAdresDialog
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geopunt4Qgis\geopunt4QgisAdresdialog.py", line 9, in 
    from .geopunt import Adres, basisregisters
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geopunt4Qgis\geopunt\__init__.py", line 23, in 
    from .basisregisters import adresMatch
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "", line 1
    (err=)
        ^
SyntaxError: invalid syntax

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.6-Hannover Hannover, bfd36fddc9 

Python pad:
C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/M0116/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by warrieka** [comment]
Yes, I a used format literals that are support with this version of python. 
I will make a minor bugfix to repair this.

**Comment by filipmahieu** [comment]
![image](https://user-images.githubusercontent.com/36032415/177260015-a05d3eb5-6c9a-4db1-9fb4-e159f1b92cb0.png)
I cannot install 2.2.8.1 now, but I can still install 2.2.8 on QGis 3.16 after deleting my plugin, which should not be the case. I should only be in the possibility to install 2.2.4 I guess to not get the bug. I still get the same notification when installing.
I added a screenshot of https://plugins.qgis.org/plugins/geopunt4Qgis/ where in line 2.2.8 Minimum QGis-version should also be 3.22.0 I guess

**Comment by warrieka** [comment]
I could not change met version number of 2.2.8, so i made a new version. 
2.2.8 is now no longer available. 
People who have a qgis-version lower then 3.2.2, can no longer install this version, people who already installed it should remove it.
