### ISSUE TITLE
Python error: plugin out of order

### ISSUE THREAD

**Issue by caje12** [warrieka/geopunt4Qgis#7]
Hi,

Since monday, when the website 'geopunt.be' was down for a few hours. The plugin stopped working. I keep getting the same error:

metaError: '[Errno 10054] An existing connection was forcibly closed by the remote host' 
Traceback (most recent call last):
  File "C:/Users/davy/.qgis2/python/plugins\geopunt4Qgis\geopunt4qgis.py", line 285, in rundatacatalog
    self.datacatalogusDlg.show()
  File "C:/Users/davy/.qgis2/python/plugins\geopunt4Qgis\geopunt4QgisDataCatalog.py", line 131, in show
    self.ui.GDIThemaCbx.addItems( ['']+ self.md.list_GDI_theme() )
  File "C:/Users/davy/.qgis2/python/plugins\geopunt4Qgis\metadata.py", line 129, in list_GDI_theme
    raise metaError( str( e.reason ))
metaError: '[Errno 10054] An existing connection was forcibly closed by the remote host'

Python versie: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS versie: 2.12.0-Lyon Lyon, cd9d645 

Any solution?

Thanks in advance,
Grt

**Comment by warrieka** [comment]
The AGIV server is blocking remote CSW connections now, nothing i can do from my end. 

I reported this to AGIV.

**Comment by caje12** [comment]
Ok, thanks!

**Comment by warrieka** [comment]
this should solved in the current release
