### ISSUE TITLE
no module  named geopunt4QgisParcel

### ISSUE THREAD

**Issue by dwalerXIII** [warrieka/geopunt4Qgis#8]
today I updated the plugin for Qgis 2.12.1 64 bit on Win7.
The following error came up:

2015-12-04T08:41:32	1	Traceback (most recent call last):
			  File "C:/OSGEO4~2/apps/qgis/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/********/.qgis2/python/plugins\geopunt4Qgis\__init__.py", line 30, in classFactory
			    from geopunt4qgis import geopunt4Qgis
			  File "C:/OSGEO4~2/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/********/.qgis2/python/plugins\geopunt4Qgis\geopunt4qgis.py", line 36, in <module>
			    from geopunt4QgisParcel import geopunt4QgisParcelDlg
			  File "C:/OSGEO4~2/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named geopunt4QgisParcel

**Comment by warrieka** [comment]
Git does not seem to handle capaitalisation unless you do, I will fix this this evening:
I need to set: 
>   git config --global core.ignorecase false
